server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  prefix: file:src/main/resources/templates/
# DATABASE
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
# JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        format_sql: true
        show_sql: true
