server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  prefix: file:src/main/resources/templates/
# DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: NONE
    logging.level:
      org.hibernate.SQL: debug
    open-in-view: false
logging:
  level:
    web: INFO